#!/bin/bash

rm -rf ./docs/*

tiddlywiki --build tiddlyjam
mv ./output/* ./docs/

tiddlywiki --build index
cp ./output/index.html ./docs/index.html
# backup to root dir
mv ./output/index.html ./index.html

