[tools]
"github:nubjs/nub" = "0.7.5"
"npm:tiddlywiki" = "5.4.1"
"npm:serve" = "14.2.6"

[tasks.dev]
description = 'Start tiddlywiki development server'
depends = ['start']

[tasks.start]
description = 'Start tiddlywiki server'
run = '''
#!/usr/bin/env bash
set -x
PORT=8080
while lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null 2>&1; do
    PORT=$((PORT + 1))
done

(sleep 2 && open -a Safari http://localhost:$PORT) &
tiddlywiki --listen port=$PORT username=TJ
'''

[tasks.preview]
description = 'Build and preview the site'
run = '''
#!/usr/bin/env bash
rm -rf output
./build
open ./docs/index.html
open ./docs/tiddlyjam/index.html
'''

[tasks.test]
description = 'Test external asset publishing'
run = './tests/build_external_images_test.sh'

[tasks.serve]
description = 'Serve the tiddlyjam'
run = '''
#!/usr/bin/env bash
serve docs/tiddlyjam
'''

[tasks.push]
description = "push to github pages"
run = '''
git add .
git commit -m "update $(date +%Y%m%d)"
git push
'''
